travis:
  secure:
    BINSTAR_TOKEN: Th8VBxcYv559P80xHbd3sgTeV98t79edXBlSx8/mbKCCzOtBw7mL7uCSqtQXQChG4w8WVivARZhgebk87wrQ6xeE1+9ePTusGTlRFFin/GSog0Gyg6+P72EiAXcZGDsszr1MDFf/VTFHC90CrVZ0L7/HT5Ae7ZLSxcpp+oxVGEsqP4fmJmz9g7sGB9SrbUaV1nyXys9vuIa6BZYHIUXsIzoiUSVNLlgjwJlHUaOofhhSAYDTw0gxJso6RUL4K59gI27jOPuPdzMSGHL7SndNA2AuYVLfw/1aHSoox+gWnav2EhneHv18wtS2+d6WPGnhf6yaqHxR03yh5V+EWj1Q8OvQcmSKJtYZ699Q6UdKUoKlvGqgg8NSxsV5soqJs58hH2t0N2lmMfPnunGaBHoaHAKDU22asVha3gPPjFT82JX8vV7s4W5aAErRj51v3iJC9Wv+ILWXM8ipKwXzbTDwBOp1VtYcMR28fsWD9OAqmdLzPrh4YL37n6B7DglNYx9Rk3CQhwu1mVt9VQ2yPuGfjmMnfkaFpMJc8jRmKx9nxVI6OfzellQoqZWuKydB1FxdZweRa9PlAQiwnOi3wQ+TEuSTqZ7xnYd+Z8Pb8B+oyY9Bz6jTRq7ehzdJCUlbaI9xRsn1lW51aPcohZVM98dN/j4OQfea+s7bDQmCeeGyUQg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
